version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=arweave_data_dev
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - postgres
    networks:
      - arweave-network-dev

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=arweave_data_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - arweave-network-dev

volumes:
  postgres-data-dev:

networks:
  arweave-network-dev:
    driver: bridge 