version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=arweave_data
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    volumes:
      - ./wallet.json:/app/wallet.json
    networks:
      - arweave-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=arweave_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - arweave-network

volumes:
  postgres-data:

networks:
  arweave-network:
    driver: bridge 